version: '3.8'

volumes:
  postgres_data: {}

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: fastify-todo-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: build
    init: true
    command: npm run start:debug
    image: ghcr.io/profl/fastify-prisma-todo-app
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fastify-todo-app?schema=public
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
    volumes:
      - ./src:/home/node/app/src:delegated
      - ./prisma:/home/node/app/prisma:delegated
      - ./jest.config.ts:/home/node/app/jest.config.ts:delegated
      - ./package.json:/home/node/app/package.json:delegated
      - ./package-lock.json:/home/node/app/package-lock.json:delegated
      - ./tsconfig.json:/home/node/app/tsconfig.json:delegated
